# Generated by Django 4.1.1 on 2022-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nami', models.CharField(max_length=50)),
                ('manzili', models.CharField(max_length=100)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bath_rooms', models.IntegerField()),
                ('maydon', models.FileField(upload_to='')),
                ('rasm', models.ImageField(upload_to='media')),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
