# Generated by Django 4.1.1 on 2022-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_rename_nami_service_nomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='maydon',
            field=models.FloatField(),
        ),
    ]
