# Generated by Django 4.1.1 on 2022-10-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_alter_service_maydon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('fami', models.CharField(max_length=50)),
                ('lavozimi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('maydoni', models.FloatField()),
                ('malumot', models.CharField(max_length=800)),
                ('rasm', models.ImageField(upload_to='media')),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('fam', models.CharField(max_length=50)),
                ('malumot', models.CharField(max_length=800)),
                ('rasmi', models.ImageField(upload_to='media')),
            ],
        ),
    ]
